# Exercise the real generated-source adapter without reconfiguring a Vita build.
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(READ "${repo}/CMakeLists.txt" build_source)
file(READ "${repo}/extern/Azel/AzelLib/town/exca/twn_exca.cpp" source_text)
string(REPLACE "\r\n" "\n" source_text "${source_text}")
set(start_marker " elseif(relative_path STREQUAL \"town/exca/twn_exca.cpp\")")
set(end_marker " elseif(relative_path STREQUAL \"town/townMainLogic.cpp\")")
string(FIND "${build_source}" "${start_marker}" adapter_start)
string(FIND "${build_source}" "${end_marker}" adapter_end)
if(adapter_start LESS 0 OR adapter_end LESS adapter_start)
 message(FATAL_ERROR "Excavation adapter boundaries missing")
endif()
math(EXPR adapter_length "${adapter_end} - ${adapter_start}")
string(SUBSTRING "${build_source}" ${adapter_start} ${adapter_length} adapter)
string(REPLACE "${start_marker}" "if(TRUE)" adapter "${adapter}")
cmake_language(EVAL CODE "${adapter}\nendif()")
if(source_text MATCHES "0x50005000")
 message(FATAL_ERROR "Native-endian pattern fill remains")
endif()
if(NOT source_text MATCHES "patternOffset < 0x2000; patternOffset \\+= 2")
 message(FATAL_ERROR "Pattern fill footprint changed")
endif()
message(STATUS "PASS: actual Excavation adapter applies; Saturn word writes preserve the 8192-byte fill")
