# Validate the actual adapter independently of the user's Vita build directory.
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(READ "${repo}/CMakeLists.txt" build_source)
file(READ "${repo}/extern/Azel/AzelLib/vdp2.cpp" source_text)
string(REPLACE "\r\n" "\n" source_text "${source_text}")
set(start_marker " elseif(relative_path STREQUAL \"VDP2.cpp\")")
set(end_marker " elseif(relative_path STREQUAL \"o_title.cpp\")")
string(FIND "${build_source}" "${start_marker}" adapter_start)
string(FIND "${build_source}" "${end_marker}" adapter_end)
if(adapter_start LESS 0 OR adapter_end LESS adapter_start)
 message(FATAL_ERROR "VDP2 adapter boundaries missing")
endif()
math(EXPR adapter_length "${adapter_end} - ${adapter_start}")
string(SUBSTRING "${build_source}" ${adapter_start} ${adapter_length} adapter)
string(REPLACE "${start_marker}" "if(TRUE)" adapter "${adapter}")
cmake_language(EVAL CODE "${adapter}\nendif()")
if(source_text MATCHES "offset & 0x1FFFFF")
 message(FATAL_ERROR "Out-of-allocation address mask remains")
endif()
if(NOT source_text MATCHES "u8 vdp2Ram\\[0x80000\\]")
 message(FATAL_ERROR "Recheck VRAM size assumption")
endif()
foreach(address 0 1 524287 524288 1048575 2097151)
 math(EXPR wrapped "${address} & (0x80000 - 1)")
 if(wrapped LESS 0 OR wrapped GREATER_EQUAL 524288)
  message(FATAL_ERROR "VRAM wrap escaped allocation")
 endif()
endforeach()
message(STATUS "PASS: actual VDP2 adapter applies; wrapping stays inside owned VRAM")
